# Author: J.A.Boogaard@hr.nl

services:
  app:
    image: app:0.1
    container_name: "app"
    tty: true
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./db/mongo-data:/data/db
      - ./db/mongo-config:/data/configdb

