-- SELECT the ORDER_ID, ORDER_DATE, and DESCRIPTION (from PRODUCT)
-- (hint, you will need to INNER JOIN CUSTOMER_ORDER and PRODUCT)

SELECT ORDER_ID, ORDER_DATE, DESCRIPTION
FROM CUSTOMER_ORDER
INNER JOIN PRODUCT
ON CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
